name: APPLICATION-CICD
on:
  
  pull_request:
    branches:
      - main_x
    paths:
      - 'terraform/*.tf'
      - '.github/workflows/infrastructure.yaml'
  
  push:
    branches:
      - development_x


jobs:

#####################################
#  APPLICATIONS
#####################################

  APPLICATION-CICD:
    #needs: [BASSICS-CICD, INFRA-CICD]

    env:
      DH_REPO_OWNER:       'jpradoar'
      DOCKER_IMAGE_NAME:   'insecure_image'

      GH_REPO_OWNER:       'jpradoar'
      GH_REPO_NAME:        'devsecops'

      BUILD_CONTEXT:       './app'
      COMMITER_NAME:       'AutoCommit'
      VULN_SEVERITY:       'CRITICAL'
      VULN_TYPE:           'os,library'
      VULN_FORMAT:         'template'
      VULN_TIMEOUT_SCAN:   '2m0s'
      VULN_SCANNERS:       'vuln,secret,misconfig,license'
      VULN_IGNORED_LIC:    'MIT'
      VULN_EXIT_CODE:      1
      TRIVY_DISABLE_VEX_NOTICE: true
      TRIVY_REPOSITORY:    'public.ecr.aws/aquasecurity/trivy-db:2'

    runs-on: ubuntu-latest
    permissions:
      contents:         write   # get the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      security-events:  write   # for github/codeql-action/upload-sarif to upload SARIF results
      actions:          read    # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status  
      issues:           write   # to create new issues in workflows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.GH_REPO_OWNER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2



#------------------------------
# CUSTOM DOCKERHUB VERSIONS
#  OJO, ESTO AÚN ESTA EN DESARROLLO, USALO BAJO TU PROPIO RESPONSABILIDAD.
#
#  REF:  https://github.com/marketplace/actions/genericsemanticversion#triggers
#------------------------------

      - name: Show last version of Docker Hub image
        id: last_version_remote_file
        run: |
          LastVersion=$(curl -s "https://hub.docker.com/v2/repositories/${{ env.DH_REPO_OWNER }}/${{ env.DOCKER_IMAGE_NAME }}/tags/?page_size=10" \
            | jq -r '.results[].name' | grep -v latest | sort -V | tail -1)
          echo "LAST_VERSION=$LastVersion" >> "$GITHUB_OUTPUT"

      - name: Generate new version with semantic version
        id: nversion
        uses: jpradoar/ga-semanticversion@v1.0.0
        with:
          COMMIT_MSG: ${{ github.event.head_commit.message }}
          VERSION: ${{ steps.last_version_remote_file.outputs.LAST_VERSION }}

#------------------------------
# FIN CUSTOM DOCKERHUB VERSIONS
#------------------------------



      #- name: Build Docker image
      #  id: docker_build
      #  uses: docker/build-push-action@v4
      #  with:
      #    context: ${{ env.BUILD_CONTEXT }}
      #    push: false
      #    tags: jpradoar/${{ env.REPO_APP }}:${{ steps.nversion.outputs.NEW_VERSION }}

      - name: Build Docker image
        id: docker_build
        run:
          docker build -t ${{ env.DH_REPO_OWNER }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.nversion.outputs.NEW_VERSION }} ${{ env.BUILD_CONTEXT }}


      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release > /dev/null
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: show docker images
        run: docker images

      - name: Run Trivy scan on Docker image
        id: trivy_scan
        continue-on-error: true
        run: |
          mkdir -p ./vuln_scans
          wget -qN https://raw.githubusercontent.com/${{ env.GH_REPO_OWNER }}/${{ env.GH_REPO_NAME }}/refs/heads/development/vuln_scans/html.tpl; 
          rm -rf ./vuln_scans/${{ env.GH_REPO_OWNER }}_vuln_scan.html; 
          trivy image \
            --scanners ${{ env.VULN_SCANNERS }} \
            --severity ${{ env.VULN_SEVERITY }} \
            --timeout ${{ env.VULN_TIMEOUT_SCAN }} \
            --pkg-types ${{ env.VULN_TYPE }} \
            --license-full \
            --ignored-licenses ${{ env.VULN_IGNORED_LIC }} \
            --format ${{ env.VULN_FORMAT }} \
            --template "@html.tpl"  \
            --exit-code ${{ env.VULN_EXIT_CODE }} \
            --db-repository ${{ env.TRIVY_REPOSITORY }} \
            --ignore-unfixed \
            -o ./vuln_scans/${{ env.DOCKER_IMAGE_NAME }}_vuln_scan.html \
            '${{ env.DH_REPO_OWNER }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.nversion.outputs.NEW_VERSION }}'


      - name: Upload vulnerability report as artifact
        if: steps.trivy_scan.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: ./vuln_scans/${{ env.DOCKER_IMAGE_NAME }}_vuln_scan.html

      - name: Show vulnerability report
        if: steps.trivy_scan.outcome == 'failure'
        run: cat ./vuln_scans/${{ env.DOCKER_IMAGE_NAME }}_vuln_scan.html

      - name: Prepare GitHub issue body
        if: steps.trivy_scan.outcome == 'failure'
        run: |
          echo "### See detailed information in: " > /tmp/vuln_info.md
          echo "<br>![](https://custom-icon-badges.demolab.com/badge/Vulnerability-detected-red.svg) ![](https://custom-icon-badges.demolab.com/badge/Affected_version-${{ steps.nversion.outputs.NEW_VERSION }}-purple.svg) <br>" >> /tmp/vuln_info.md
          echo "* Detected in image: [${{ env.DOCKER_IMAGE_NAME }}](https://hub.docker.com/repository/docker/${{ env.DH_REPO_OWNER }}/${{ env.DOCKER_IMAGE_NAME }}/general)" >> /tmp/vuln_info.md
          echo "* Detected in commit: ${{ github.sha }}" >> /tmp/vuln_info.md
          echo "* Vulnerability report: [vuln_report](https://${{ env.GH_REPO_OWNER }}.github.io/${{ env.GH_REPO_NAME }}/vuln_scans/${{ env.DOCKER_IMAGE_NAME }}_vuln_scan.html)" >> /tmp/vuln_info.md

# PARA MAIN
# echo "* Vulnerability report: [vuln_report](https://github.com/${{ github.repository }}/blob/main/vuln_scans/${{ env.DOCKER_IMAGE_NAME }}_vuln_scan.html)" >> /tmp/vuln_info.md

      - name: Commit vulnerability report to repo
        if: steps.trivy_scan.outcome == 'failure'
        uses: EndBug/add-and-commit@v9
        with:
          message: 'AutoCommit: upload vuln scan report'
          add: './vuln_scans/${{ env.DOCKER_IMAGE_NAME }}_vuln_scan.html'



#---------------------
# Importante, requiere que tengas el label para el issue
# ref:  https://github.com/jpradoar/devsecops/labels
# Si no lo tenes o no lo queres poner, comenta la linea de "--label vulnerability"
#---------------------

      - name: Create GitHub issue for vulnerability
        if: steps.trivy_scan.outcome == 'failure'
        run: |
          gh issue create \
            --repo ${{ github.repository }} \
            --title ":skull: [vuln] Vulnerability in image ${{ env.DOCKER_IMAGE_NAME }}:${{ steps.nversion.outputs.NEW_VERSION }}" \
            --body-file '/tmp/vuln_info.md' \
            --assignee "${{ env.DH_REPO_OWNER }}" \
            --label bug \
            --label vulnerability
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image (only if scan passes)
        if: steps.trivy_scan.outcome == 'success'
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.BUILD_CONTEXT }}
          push: true
          tags: ${{ env.DH_REPO_OWNER }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.nversion.outputs.NEW_VERSION }}


            
      - name: Slack Notification - Docker image built
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: '#2c74e8'
          SLACK_TITLE: ':img_docker: Docker image built: [ ${{ env.DOCKER_IMAGE_NAME }}:${{ steps.nversion.outputs.NEW_VERSION }} ]'
          SLACK_MESSAGE: 'URL: https://hub.docker.com/repository/docker/${{ env.DH_REPO_OWNER }}/${{ env.DOCKER_IMAGE_NAME }}'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WH_BUILDS }}


      - name: Slack Notification - Vulnerabilities detected
        if: steps.trivy_scan.outcome == 'failure'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: '#2c74e8'
          SLACK_TITLE: ':skull: DockerHub Push blocked - Vulnerabilities in: [ ${{ env.DOCKER_IMAGE_NAME }}:${{ steps.nversion.outputs.NEW_VERSION }} ]'
          SLACK_MESSAGE: 'Vulnerabilities found in image ${{ env.REPO_APP }}. Please check the report in: https://jpradoar.github.io/devsecops/vuln_scans/${{ env.DOCKER_IMAGE_NAME }}_vuln_scan.html'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WH_SECURITY }}


   #SLACK_TITLE: ':skull: Vulnerability detected in: [ ${{ env.DOCKER_IMAGE_NAME }}:${{ steps.nversion.outputs.NEW_VERSION }} ] - image **was not pushed** to Docker Hub.'


# PARA MAIN
# SLACK_MESSAGE: 'Vulnerabilities found in image ${{ env.REPO_APP }}. Please check the [report](https://github.com/${{ github.repository }}/blob/main/vuln_scans/${{ env.DOCKER_IMAGE_NAME }}_vuln_scan.html)'

