name: APPLICATION-CICD
on:
  push:
    branches:
      - development_x
    paths:
      - '.github/workflows/test.yaml'

env:
  SLACK_CHANNEL:    'general'

jobs:

#####################################
#  APPLICATIONS
#####################################

  APPLICATION-CICD:
    #needs: [BASSICS-CICD, INFRA-CICD]

    env:
      DH_REPO_OWNER:       'jpradoar'
      DH_REPO_APP:         'insecure_image'
      GH_REPO_OWNER:       'jpradoar'
      GH_REPO_NAME:        'devsecops'
      BUILD_CONTEXT:       './app'
      COMMITER_NAME:       'AutoCommit'
      VULN_SEVERITY:       'CRITICAL'
      VULN_TYPE:           'os,library'
      VULN_FORMAT:         'template'
      VULN_TIMEOUT_SCAN:   '2m0s'
      VULN_SCANNERS:       'vuln,secret,misconfig,license'
      VULN_IGNORED_LIC:    'MIT'
      VULN_EXIT_CODE:      1
      TRIVY_DISABLE_VEX_NOTICE: true
      TRIVY_REPOSITORY:    'public.ecr.aws/aquasecurity/trivy-db:2'

    runs-on: ubuntu-latest
    permissions:
      contents:         write   # get the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      security-events:  write   # for github/codeql-action/upload-sarif to upload SARIF results
      actions:          read    # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status  
      issues:           write   # to create new issues in workflows

    steps:

      - name: test
        run: |
          echo ${{ github.repository }}



      - name: Slack Notification - Docker image built
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: '#2c74e8'
          SLACK_MESSAGE: 'CANAL GENERAL'
          SLACK_TITLE: 'hola general'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}


      - name: Slack Notification - Docker image built
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: '#2c74e8'
          SLACK_MESSAGE: 'CANAL BUILDS'
          SLACK_TITLE: 'Hola build'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WH_BUILDS }}            

      - name: Slack Notification - Docker image built
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: '#2c74e8'
          SLACK_MESSAGE: 'CANAL SECURITY'
          SLACK_TITLE: 'Hola security'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WH_SECURITY }}            


            
